### PR TITLE
Add allStoredCards & storedCard queries

### PR DESCRIPTION
**Pull request by OoXoSoO**
Add 2 new queries in paymentX product

### CODE REVIEW

**Comment by OoXoSoO** [comment]
Sorry @arquio! 
Done!

**Comment by arquio** [comment]
Perfect @OoXoSoO.

Tomorrow we need review the "organization" fields ;P

**Comment by OoXoSoO** [comment]
@arquio, can you review this PR?

**Comment by arquio** [comment]
Please @OoXoSoO review the conflict

**Pull request merged**
